import { RouteProp, useRoute } from "@react-navigation/native";
import { useNavigation } from "@react-navigation/native";
import { useEffect, useState } from "react";
import { GameScreenNavigationProp } from "../../types/navigation";

interface RouteParams {
	userNumber?: number;
}

export default function useApp() {
	const [isDisabled, setisDisabled] = useState(true);
	const [guessRounds, setGuessRounds] = useState(0);
	const [computerChances, setComputerChances] = useState(7);
	const [isLessThan, setisLessThan] = useState(99);
	const [isMoreThan, setisMoreThan] = useState(1);
	const [randomNumberGenerated, setRandomNumberGenerated] = useState(0);

	const route = useRoute<RouteProp<{ params: RouteParams; }, "params">>();
	const userNumber = route.params?.userNumber || 0;
	const navigation = useNavigation<GameScreenNavigationProp>();

	useEffect(() => {
		console.log("more: " + isMoreThan, "less: " + isLessThan);
	}, [isLessThan, isMoreThan]);

	function handlerPlayerVictory(
		playerNumber: number,
		computerNumber: number
	) {
		if (playerNumber === computerNumber) {
			navigation.navigate("WinScreen", {
				userNumber: userNumber,
				guessRounds: guessRounds,
			});
		}
		return;
	}

	function handleLoss(screen: string) {
		if (screen === "GameOverComputerScreen") {
			navigation.navigate("GameOverComputerScreen");
		}
		if (screen === "GameOverPlayerScreen") {
			navigation.navigate("GameOverPlayerScreen");
			return;
		}
	}

	function randomNumberComputer(
		lessThan = isLessThan,
		moreThan = isMoreThan
	) {
		const randomNumber = Math.floor(
			Math.random() * (moreThan - lessThan + 1) + lessThan
		);

		console.log("generated by computer:", randomNumber);
		setRandomNumberGenerated(randomNumber);

		if (computerChances === 0) {
			handleLoss("GameOverComputerScreen");
			return;
		}

		if (randomNumber === userNumber) {
			handlerPlayerVictory(userNumber, randomNumber);
			return;
		}

		if (guessRounds < 7) {
			console.log("Computer guessed the wrong number");
			setisDisabled(false);
			setGuessRounds((prev) => prev + 1);
			setComputerChances((prev) => prev - 1);
			setRandomNumberGenerated(randomNumber);
			return;
		}
	}

	function guessNumberMinHandler() {
		if (randomNumberGenerated < userNumber) {
			console.log("The guessed number is higher than the user number");
			handleLoss("GameOverPlayerScreen");
			return;
		} else {
			setisDisabled((prev) => !prev);
			setisLessThan(randomNumberGenerated);
		}
	}

	function guessNumberMaxHandler() {
		if (randomNumberGenerated > userNumber) {
			console.log("The guessed number is lower than the user number");
			handleLoss("GameOverPlayerScreen");
			return;
		} else {
			setisDisabled((prev) => !prev);
			setisMoreThan(randomNumberGenerated);
		}
	}

	function newGameHandler() {
		setisDisabled(true);
		setRandomNumberGenerated(0);
		setGuessRounds(0);
		setComputerChances(7);
		setisLessThan(99);
		setisMoreThan(1);
		navigation.push("Home");
	}

	return {
		randomNumberComputer,
		newGameHandler,
		guessNumberMinHandler,
		guessNumberMaxHandler,
		userNumber2: userNumber,
		isDisabled,
		guessRounds,
		computerChances,
		isLessThan,
		isMoreThan,
		randomNumberGenerated,
	};
}
