import { RouteProp, useRoute } from "@react-navigation/native";
import { useNavigation } from "@react-navigation/native";
import { useEffect, useState } from "react";
import { GameScreenNavigationProp } from "../../types/navigation";

interface RouteParams {
	userNumber?: number;
}

export default function useApp() {
	const [isvisible, setIsVisible] = useState(false);
	const [isDisabled, setisDisabled] = useState(true);
	const [guessRounds, setGuessRounds] = useState(0);
	const [isLessThan, setisLessThan] = useState(99);
	const [isMoreThan, setisMoreThan] = useState(1);
	const [randomNumberGenerated, setRandomNumberGenerated] = useState(0);

	const route = useRoute<RouteProp<{ params: RouteParams }, "params">>();
	const userNumber2 = route.params?.userNumber;
	const navigation = useNavigation<GameScreenNavigationProp>();

	useEffect(() => {
		console.log("more: " + isMoreThan, "less: " + isLessThan);
	}, [isLessThan, isMoreThan]);

	function randomNumberComputer(
		lessThan = isLessThan,
		moreThan = isMoreThan
	) {
		const randomNumber = Math.floor(
			Math.random() * (moreThan - lessThan + 1) + lessThan
		);
		console.log("generated by computer:", randomNumber);
		setRandomNumberGenerated(randomNumber);
		if (randomNumber === userNumber2) {
			navigation.navigate("WinScreen", {
				userNumber: userNumber2,
				guessRounds: guessRounds,
			});
			return;
		} else {
			console.log("Computer guessed the wrong number");
			setisDisabled(false);
			setGuessRounds((prev) => prev + 1);
			setRandomNumberGenerated(randomNumber);
			return;
		}
	}

	function guessNumberMinHandler() {
		setisDisabled((prev) => !prev);
		setisLessThan(randomNumberGenerated);
	}

	function guessNumberMaxHandler() {
		setisDisabled((prev) => !prev);
		setisMoreThan(randomNumberGenerated);
	}

	function newGameHandler() {
		setIsVisible((previsousState) => !previsousState);
		setGuessRounds(0);
		setisLessThan(1);
		setisMoreThan(99);
	}

	return {
		randomNumberComputer,
		newGameHandler,
		guessNumberMinHandler,
		guessNumberMaxHandler,
		userNumber2,
		isvisible,
		isDisabled,
		guessRounds,
		isLessThan,
		isMoreThan,
		randomNumberGenerated,
	};
}
