import { RouteProp, useRoute } from "@react-navigation/native";
import { useNavigation } from "@react-navigation/native";
import { useState } from "react";
import { GameScreenNavigationProp } from "../../types/navigation";

interface RouteParams {
	userNumber?: number;
}
interface randomNumberComputer {
	min: number;
	max: number;
}

export default function useApp() {
	const [isvisible, setIsVisible] = useState(false);
	const [guessRounds, setGuessRounds] = useState(0);
	const [guessNumberMin, setGuessNumberMin] = useState(1);
	const [guessNumberMax, setGuessNumberMax] = useState(99);
	const [randomNumberGenerated, setRandomNumberGenerated] = useState(0);

	const route = useRoute<RouteProp<{ params: RouteParams }, "params">>();
	const userNumber2 = route.params?.userNumber;
	const navigation = useNavigation<GameScreenNavigationProp>();

	function randomNumberComputer({ min, max }: randomNumberComputer) {
		const randomNumber = Math.floor(Math.random() * (max - min + 1) + min);
		console.log("generated by computer:", randomNumber);
		setRandomNumberGenerated(randomNumber);
		if (randomNumber === userNumber2) {
			navigation.navigate("WinScreen", {
				userNumber: userNumber2,
				guessRounds: guessRounds,
			});
			return;
		} else {
			console.log("Computer guessed the wrong number");
			setGuessRounds((prev) => prev + 1);
			setRandomNumberGenerated(randomNumber);
			return;
		}
	}

	function guessNumberMinHandler() {
		setGuessNumberMin(randomNumberGenerated);
	}

	function guessNumberMaxHandler() {
		setGuessNumberMax(randomNumberGenerated);
	}

	function newGameHandler() {
		setIsVisible((previsousState) => !previsousState);
		setGuessRounds(0);
		setGuessNumberMin(1);
		setGuessNumberMax(99);
	}

	return {
		randomNumberComputer,
		newGameHandler,
		guessNumberMinHandler,
		guessNumberMaxHandler,
		userNumber2,
		isvisible,
		guessRounds,
		guessNumberMin,
		guessNumberMax,
		randomNumberGenerated,
	};
}
